// Renders every variant in variants.yaml to out/<variant>.tex and .pdf via pdflatex.
//   node build.mjs            build all variants
//   node build.mjs quant      build one
//   node build.mjs --check    build all, then fail on overfull boxes, >1 page, or missing bullets
import { execFileSync } from 'node:child_process';
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { parse } from 'yaml';
import { selectVariant } from './select.mjs';

const ROOT = import.meta.dirname;
// RESUME_VARIANTS adds variants from a file kept outside the repository (role-specific
// resumes); RESUME_OUT sends their output there too.
const OUT = process.env.RESUME_OUT ?? path.join(ROOT, 'out');
const load = (f) => parse(readFileSync(path.join(ROOT, f), 'utf8'));
const master = load('master.yaml');
const extra = process.env.RESUME_VARIANTS ? parse(readFileSync(process.env.RESUME_VARIANTS, 'utf8')) : {};
const variants = process.env.RESUME_VARIANTS ? extra : { ...load('variants.yaml'), ...extra };

const args = process.argv.slice(2);
const check = args.includes('--check');
const keys = args.filter((a) => !a.startsWith('--'));
const targets = keys.length ? keys : Object.keys(variants);

const TEX_ESCAPES = { '\\': '\\textbackslash{}', '&': '\\&', '%': '\\%', $: '\\$', '#': '\\#', _: '\\_', '{': '\\{', '}': '\\}', '~': '\\textasciitilde{}', '^': '\\textasciicircum{}' };
const tex = (s = '') =>
  String(s)
    .replace(/[\\&%$#_{}~^]/g, (c) => TEX_ESCAPES[c])
    .replace(/ -- /g, ' -- ')
    .replace(/(\d),(\d{3})/g, '$1{,}$2');
const link = (text, url) => (url ? `\\href{${url}}{${tex(text)}}` : tex(text));

function renderEntry(section, e) {
  const bullets = e.bullets.length
    ? `\\resumeListStart\n${e.bullets.map((b) => `  \\resumeItem{${tex(b.text)}}`).join('\n')}\n\\resumeListEnd\n`
    : '';
  if (section.kind === 'projects') {
    const priv = e.visibility === 'private' ? ' {\\normalfont\\small\\textit{(private)}}' : '';
    const stack = e.stack ? ` $\\mid$ {\\normalfont ${tex(e.stack)}}` : '';
    return `\\resumeProject{${link(e.title, e.url)}${priv}${stack}}{${tex(e.right)}}\n${bullets}`;
  }
  return `\\resumeSubheading{${link(e.title, e.url)}}{${tex(e.right)}}{${tex(e.subtitle)}}{${tex(e.location)}}\n${bullets}`;
}

function renderVariant(view) {
  const p = view.person;
  const contact = p.contact.map((c) => link(c.label, c.url)).join(' $\\mid$\n  ');
  const body = view.sections
    .map((s) => {
      const head = `\\section{${tex(s.title)}}\n${s.note ? `{\\small\\textit{${tex(s.note)}}}\\\\[2pt]\n` : ''}`;
      if (s.kind === 'skills') {
        return `${head}\\small\n${s.lines.map((l) => `\\textbf{${tex(l.label)}:} ${tex(l.items)}`).join(' \\quad\n')}\n`;
      }
      return head + s.entries.map((e) => renderEntry(s, e)).join('\n');
    })
    .join('\n');
  return `% Generated by build.mjs from master.yaml + variants.yaml (variant: ${view.key}). Do not edit.
\\documentclass[letterpaper,11pt]{article}
\\input{resume_common.tex}
\\begin{document}

\\begin{center}
  {\\LARGE\\bfseries ${tex(p.name)}}\\\\[2pt]
  ${view.headline ? `{\\large\\bfseries ${tex(view.headline)}}\\\\[3pt]\n  ` : ''}\\small ${contact}
\\end{center}

${body}
\\end{document}
`;
}

mkdirSync(OUT, { recursive: true });
copyFileSync(path.join(ROOT, 'resume_common.tex'), path.join(OUT, 'resume_common.tex'));
const failures = [];
for (const key of targets) {
  if (!variants[key]) throw new Error(`Unknown variant: ${key}`);
  const view = selectVariant(master, variants, key);
  const name = `nyx_haile_${key.replace(/-/g, '_')}`;
  writeFileSync(path.join(OUT, `${name}.tex`), renderVariant(view));
  for (let pass = 0; pass < 2; pass++) {
    execFileSync('pdflatex', ['-interaction=nonstopmode', '-halt-on-error', `${name}.tex`], { cwd: OUT, stdio: 'ignore' });
  }
  const log = readFileSync(path.join(OUT, `${name}.log`), 'utf8');
  const pages = Number(/Pages:\s+(\d+)/.exec(execFileSync('pdfinfo', [`${name}.pdf`], { cwd: OUT, encoding: 'utf8' }))?.[1]);
  const norm = (t) => t.replace(/[\u2018\u2019]/g, "'").replace(/[\u201c\u201d]/g, '"').replace(/\s+/g, ' ');
  const text = norm(execFileSync('pdftotext', ['-layout', `${name}.pdf`, '-'], { cwd: OUT, encoding: 'utf8' }));
  const bullets = view.sections.flatMap((s) => s.entries ?? []).flatMap((e) => e.bullets);
  const missing = bullets.filter((b) => !text.includes(norm(b.text).slice(0, 40)));
  const overfull = (log.match(/Overfull \\hbox/g) ?? []).length;
  const maxPages = variants[key].maxPages ?? 1;
  console.log(`${key}: ${pages} page(s), ${bullets.length} bullets, ${overfull} overfull, ${missing.length} missing from text layer`);
  if (check && (pages > maxPages || overfull || missing.length)) {
    failures.push(`${key}: pages=${pages}/${maxPages} overfull=${overfull} missing=${missing.map((b) => b.id).join(',')}`);
  }
}
if (failures.length) {
  console.error(`check failed:\n  ${failures.join('\n  ')}`);
  process.exit(1);
}
